// Pure, DB-free commercial helpers: Purchase Order pricing, references, money
// formatting and PDF body composition. Pricing basis: per-school annual price ×
// term (years) − optional discount. Unit-tested in tests/commerce.test.ts.

export type PoPricingInput = { unitPrice: number; termYears: number; discountPct: number };
export type PoPricing = { gross: number; discountAmount: number; finalCost: number };

/** Compute a Purchase Order total (all amounts in minor units / pence).
 *  gross = unitPrice × termYears; discount clamped 0–100%; finalCost >= 0. */
export function computePoCost(input: PoPricingInput): PoPricing {
  const unit = Math.max(0, Math.round(Number(input.unitPrice) || 0));
  const years = Math.max(1, Math.round(Number(input.termYears) || 1));
  const pct = Math.min(100, Math.max(0, Number(input.discountPct) || 0));
  const gross = unit * years;
  const discountAmount = Math.round(gross * (pct / 100));
  const finalCost = Math.max(0, gross - discountAmount);
  return { gross, discountAmount, finalCost };
}

/** System-generated PO reference, e.g. PO-2026-0007. */
export function poReference(seq: number, year: number): string {
  return `PO-${year}-${String(Math.max(1, Math.round(seq))).padStart(4, "0")}`;
}

const SYMBOLS: Record<string, string> = { GBP: "£", USD: "$", EUR: "€" };
/** Format minor units as a currency string, e.g. 216000 -> "£2,160.00". */
export function formatMoney(pence: number, currency = "GBP"): string {
  const sym = SYMBOLS[currency] ?? "";
  const v = (Math.round(pence) / 100).toFixed(2);
  // thousands separators on the integer part
  const [int, dec] = v.split(".");
  const withSep = int.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  return `${sym}${withSep}.${dec}`;
}

// Valid PO status transitions used by the action menu / API.
export const PO_STATUSES = ["draft", "sent", "cancelled", "accepted"] as const;
export type PoStatus = (typeof PO_STATUSES)[number];
export function canSendPo(status: string): boolean { return status === "draft" || status === "sent"; }
export function canEditPo(status: string): boolean { return status === "draft" || status === "sent"; }
export function canCancelPo(status: string): boolean { return status !== "cancelled"; }

export type PoLike = {
  reference: string; schoolName: string; planName: string; packageType: string;
  userQuantity: number; termYears: number; unitPrice: number; discountPct: number;
  discountAmount: number; finalCost: number; currency: string; status: string;
  notes?: string | null; createdAt?: Date | string;
};

/** Compose the text body (paragraphs) for a PO PDF. The caller wraps this with
 *  the PDF renderer. Kept pure so it can be asserted in tests. */
export function poPdfParagraphs(po: PoLike, meta: { generatedBy?: string; trustName?: string | null; generatedAt?: string } = {}): string[] {
  const money = (p: number) => formatMoney(p, po.currency);
  const lines: string[] = [];
  lines.push(`Purchase Order: ${po.reference}`);
  if (meta.generatedAt) lines.push(`Date: ${meta.generatedAt}`);
  lines.push("");
  lines.push(`School / Tenant: ${po.schoolName}`);
  if (meta.trustName) lines.push(`Trust: ${meta.trustName}`);
  lines.push(`Plan: ${po.planName}`);
  lines.push(`Package type: ${po.packageType}`);
  lines.push(`User quantity: ${po.userQuantity}`);
  lines.push(`Subscription term: ${po.termYears} year${po.termYears === 1 ? "" : "s"}`);
  lines.push("");
  lines.push(`Unit price (per school / year): ${money(po.unitPrice)}`);
  lines.push(`Subtotal (${po.termYears} × ${money(po.unitPrice)}): ${money(po.unitPrice * po.termYears)}`);
  if (po.discountPct > 0) lines.push(`Discount (${po.discountPct}%): -${money(po.discountAmount)}`);
  lines.push(`Final cost: ${money(po.finalCost)}`);
  lines.push("");
  lines.push(`Status: ${po.status}`);
  if (po.notes) { lines.push(""); lines.push("Notes:"); lines.push(po.notes); }
  if (meta.generatedBy) { lines.push(""); lines.push(`Generated by: ${meta.generatedBy}`); }
  return lines;
}
